### ISSUE TITLE
Library media box misaligned

### ISSUE THREAD

**Issue by Coocla33** [wopian/hibari#171]
Version: 0.3.1-30-g69ff6e8
Operating System: Windows 10
Browser: Chrome
Browser Version: X

This is not aligned right...
http://prntscr.com/f36cit

Steps to replicate:
0. Set locale to NL
1. User: Coocla33
2. Go to library
3. Hover over first library entrie.

**Comment by wopian** [comment]
This is a known issue with an unknown cause related to the production build 😢

It displays fine when run locally

**Comment by wopian** [comment]
Oh yeah, the dutch strings are too long for how I originally designed it and wrapping 😨
